Repository FEUP-ESOF-2020-21/open-cx-t4g1-grupo-1, pull requests merged in 2020-11, with the labels that each got.

#7 Talks Schedule Screen
  adov_flutter/lib/app.dart
  adov_flutter/lib/models/Day.dart
  adov_flutter/lib/models/location.dart
  adov_flutter/lib/models/location_fact.dart
  adov_flutter/lib/models/talk.dart
  adov_flutter/lib/screens/add_talk/add_talk.dart
  adov_flutter/lib/screens/locations/locations.dart
  adov_flutter/lib/screens/locations/tile_overlay.dart
  adov_flutter/lib/screens/talk_detail/talk_detail.dart
  adov_flutter/lib/screens/talks_schedule/talks_schedule.dart
  adov_flutter/lib/widgets/date_time_picker.dart
  adov_flutter/lib/widgets/talk_container.dart
  adov_flutter/lib/widgets/talk_day.dart
  adov_flutter/lib/widgets/talk_tile.dart
  adov_flutter/pubspec.yaml
  adov_flutter/test/unit/location_test.dart
  adov_flutter/test/unit/test_talks.dart
  adov_flutter/test_driver/app_test.dart
Labels: feature, ui

#11 Small Refactoring - Add Talk Screen
  adov_flutter/lib/input_decorators/form_input_decorator.dart
  adov_flutter/lib/screens/add_talk/add_talk.dart
Labels: refactoring

#28 Homepage Screen
  adov_flutter/android/app/src/main/AndroidManifest.xml
  adov_flutter/lib/app.dart
  adov_flutter/lib/input_decorators/form_input_decorator.dart
  adov_flutter/lib/models/Conference.dart
  adov_flutter/lib/models/talk.dart
  adov_flutter/lib/screens/add_talk/add_talk.dart
  adov_flutter/lib/screens/home_screen/conference_details.dart
  adov_flutter/lib/screens/home_screen/conference_sponsors.dart
  adov_flutter/lib/screens/home_screen/conference_stats.dart
  adov_flutter/lib/screens/home_screen/home_screen.dart
  adov_flutter/lib/screens/home_screen/next_talk.dart
  adov_flutter/lib/screens/home_screen/next_talk_container.dart
  adov_flutter/lib/screens/talk_detail/talk_detail.dart
  adov_flutter/lib/screens/talks_schedule/talks_schedule.dart
  adov_flutter/lib/style.dart
  adov_flutter/lib/widgets/talk_container.dart
Labels: feature, ui

#12 Database Configuration - Firestore
  adov_flutter/android/app/build.gradle
  adov_flutter/android/app/google-services.json
  adov_flutter/android/build.gradle
  adov_flutter/lib/app.dart
  adov_flutter/lib/database.dart
  adov_flutter/lib/main.dart
  adov_flutter/lib/models/talk.dart
  adov_flutter/lib/screens/add_talk/add_talk.dart
  adov_flutter/lib/screens/talk_detail/talk_detail.dart
  adov_flutter/lib/screens/talks_schedule/talks_schedule.dart
  adov_flutter/pubspec.yaml
  adov_flutter/test/unit/test_talks.dart
  adov_flutter/test_driver/app_test.dart
Labels: db

#31 improved use cases on report
  docs/readme.md
Labels: documentation, report

#32 Login Page
  adov_flutter/lib/app.dart
  adov_flutter/lib/screens/home_screen/home_screen.dart
  adov_flutter/lib/screens/login/animated_text.dart
  adov_flutter/lib/screens/login/login.dart
  adov_flutter/lib/screens/login/welcome_screen.dart
  adov_flutter/pubspec.yaml
Labels: db, feature
