Repository FEUP-ESOF-2020-21/open-cx-t4g1-grupo-1, pull requests merged in 2020-12, with the labels that each got.

#34 Cloud Functions and Notifications
  adov_flutter/lib/app.dart
  adov_flutter/lib/main.dart
  adov_flutter/lib/screens/login/welcome_screen.dart
  adov_flutter/pubspec.yaml
  cloud_functions/.firebaserc
  cloud_functions/.gitignore
  cloud_functions/firebase.json
  cloud_functions/functions/.eslintrc.json
  cloud_functions/functions/.gitignore
  cloud_functions/functions/index.js
  cloud_functions/functions/package-lock.json
  cloud_functions/functions/package.json
Labels: db, feature, ui

#40 App Logo
  adov_flutter/android/app/src/main/ic_launcher-playstore.png
  adov_flutter/android/app/src/main/res/drawable-hdpi/ic_launcher_background.png
  adov_flutter/android/app/src/main/res/drawable-hdpi/ic_launcher_foreground.png
  adov_flutter/android/app/src/main/res/drawable-mdpi/ic_launcher_background.png
  adov_flutter/android/app/src/main/res/drawable-mdpi/ic_launcher_foreground.png
  adov_flutter/android/app/src/main/res/drawable-xhdpi/ic_launcher_background.png
  adov_flutter/android/app/src/main/res/drawable-xhdpi/ic_launcher_foreground.png
  adov_flutter/android/app/src/main/res/drawable-xxhdpi/ic_launcher_background.png
  adov_flutter/android/app/src/main/res/drawable-xxhdpi/ic_launcher_foreground.png
  adov_flutter/android/app/src/main/res/drawable-xxxhdpi/ic_launcher_background.png
  adov_flutter/android/app/src/main/res/drawable-xxxhdpi/ic_launcher_foreground.png
  adov_flutter/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  adov_flutter/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  adov_flutter/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  adov_flutter/android/app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  adov_flutter/android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  adov_flutter/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  adov_flutter/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  adov_flutter/android/app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  adov_flutter/android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  adov_flutter/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  adov_flutter/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  adov_flutter/android/app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  adov_flutter/android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  adov_flutter/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  adov_flutter/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  adov_flutter/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  adov_flutter/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  adov_flutter/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  adov_flutter/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  adov_flutter/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  adov_flutter/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  adov_flutter/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  adov_flutter/assets/icon/adov_bg.png
  adov_flutter/assets/icon/adov_fg.png
  adov_flutter/assets/icon/adov_icon.png
  adov_flutter/assets/icon/icon_model.ai
  adov_flutter/ios/Runner.xcodeproj/project.pbxproj
  adov_flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  adov_flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  adov_flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  adov_flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  adov_flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  adov_flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  adov_flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  adov_flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  adov_flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  adov_flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  adov_flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  adov_flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  adov_flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  adov_flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  adov_flutter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
Labels: ui

#38 dados de talks atualizados | Testes gherkin
  adov_flutter/lib/database/talks_database.dart
  adov_flutter/lib/screens/home_screen/conference_sponsors.dart
  adov_flutter/lib/screens/home_screen/home_screen.dart
  adov_flutter/lib/screens/login/login.dart
  adov_flutter/lib/screens/login/welcome_screen.dart
  adov_flutter/lib/screens/talks_schedule/talks_schedule.dart
  adov_flutter/lib/widgets/talk_container.dart
  adov_flutter/pubspec.yaml
  adov_flutter/test_driver/app.dart
  adov_flutter/test_driver/app_test.dart
  adov_flutter/test_driver/feature/Enter.feature
  adov_flutter/test_driver/feature/Login.feature
  adov_flutter/test_driver/feature/Logout.feature
  adov_flutter/test_driver/feature/Schedule.feature
  adov_flutter/test_driver/report.json
  adov_flutter/test_driver/steps/test_steps.dart
  adov_flutter/test_driver/test_config.dart
Labels: db

#42 Report for Delivery
  adov_flutter/lib/screens/home_screen/home_screen.dart
  docs/readme.md
  docs/uml/physical-architecture.jpg
Labels: documentation
